# wrangler.toml
name = "ai-intake" # This will be part of your worker's URL, e.g., ai-intake.<YOUR_ACCOUNT>.workers.dev
main = "src/index.js"
compatibility_date = "2025-05-09" # Use the date provided or a more recent one

[[routes]]
pattern = "admagent2025.com/*"
zone_name = "admagent2025.com"

[vars]
# OPENAI_KEY will be set as a secret, not directly here.
# This 'dummy' value here is just a placeholder and won't be used if the secret is set.
# OPENAI_KEY = "dummy_this_will_be_overridden_by_secret"