# wrangler.toml
name = "ai-intake" # This will be part of your worker's URL, e.g., ai-intake.<YOUR_ACCOUNT>.workers.dev
main = "src/index.js"
compatibility_date = "2025-05-09" # Use the date provided or a more recent one

[[routes]]
pattern = "admagent2025.com/summarize"
zone_name = "admagent2025.com"

[[routes]]
pattern = "admagent2025.com/process"
zone_name = "admagent2025.com"

[[routes]]
pattern = "admagent2025.com/store-idea"
zone_name = "admagent2025.com"

[[d1_databases]]
binding = "DB"
database_name = "adm-ai-ideas-db"
database_id = "8c18f48a-5c7b-4171-8d96-266b09dc2893"

[vars]
# OPENAI_KEY will be set as a secret, not directly here.
# This 'dummy' value here is just a placeholder and won't be used if the secret is set.
# OPENAI_KEY = "dummy_this_will_be_overridden_by_secret"